[package]
name          = "mio-misc"
version       = "2.0.6"
license       = "MIT OR Apache-2.0"
authors       = ["Onur Ozduygu"]
description   = "Misc components for use with Mio"
documentation = "https://docs.rs/mio-misc"
repository    = "https://github.com/dimbleby/mio-extras"
readme        = "README.md"
keywords      = ["io", "async", "non-blocking"]
categories    = ["asynchronous"]
exclude       = [".gitignore"]
edition       = "2018"

[dependencies]
mio = {version ="0.7", features = ["os-poll", "tcp"]}
crossbeam = "0.7"
crossbeam-queue = "0.2"

[[test]]
name = "test"
path = "test/mod.rs"
